"""Build a clean zip of the project for sharing with a friend.

Excludes the bundled Python runtime (``_internal/`` ~932 MB), build artefacts,
local logs, and personal data. Scrubs API tokens / Discord webhooks / dev
credentials from cfg files so nothing private leaks through. Emits a README
explaining how to install on the friend's machine.

Usage:
    python tools/build_share_zip.py [output_zip_path]
"""

from __future__ import annotations

import os
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = ROOT.parent / "PylaAI-test-share.zip"

# ------------------------------------------------------------------
# What to skip
# ------------------------------------------------------------------
EXCLUDE_DIR_NAMES = {
    "_internal",                # 932 MB PyInstaller bundle for setup.exe
    "__pycache__",
    "build",
    "pylaai_op_xxz.egg-info",
    "logs",                     # local log history
    "instances",                # local multi-emulator state
    "debug_frames",
    ".git",
    ".vscode",
    ".idea",
    "fork", "FORK",             # reference fork, not needed by friend
    "runs",
    "tools/runs",
    ".pytest_cache",
    "node_modules",             # tooling-only deps for local audit scripts
    "Desing Promt",             # designer's prototype workspace, prod uses web_ui/
    # Local test fixtures: personal account screenshots + auto-annotated
    # debug frames. They're useful for our regression dev work but not for
    # a friend's install; they also leak account UI hints.
    "TestScreenshot",
    "LobbyBrawlerTets",
    "_annotated",
}

EXCLUDE_FILE_RELPATHS = {
    "latest_brawler_data.json",
    "cfg/match_log.jsonl",      # match history, can be MB
    "cfg/sessions.jsonl",
    "cfg/adaptive_state.json",
    "cfg/login.toml",           # personal license-style key
    "cfg/match_history.toml",
    "codes.txt",                # unrelated personal note
    "test.txt",
    "setup.exe",                # needs _internal which we excluded
    ".gitignore",
}

EXCLUDE_FILE_SUFFIXES = (
    ".pyc", ".pyo", ".pyd",
)

# ------------------------------------------------------------------
# What to scrub before zipping
# ------------------------------------------------------------------
SCRUBBED_FILES = {
    "cfg/brawl_stars_api.toml": '''api_token = ""
player_tag = "#YOURTAG"
timeout_seconds = 15
auto_refresh_token = false
developer_email = ""
developer_password = ""
public_ip_service = "https://api.ipify.org"
key_name_prefix = "PylaAI Auto"
key_description = "Auto-generated by PylaAI for the current public IP."
delete_old_auto_tokens = true
delete_all_tokens = false
last_public_ip = ""
''',
    "cfg/webhook_config.toml": '''webhook_url = ""
discord_id = ""
username = "PylaAI"
send_match_summary = false
include_screenshot = true
ping_when_stuck = false
ping_when_target_is_reached = false
ping_every_x_match = 0
ping_every_x_minutes = 0
''',
}


def scrub_general_config(text: str) -> str:
    """Strip the personal webhook / player tag / public IP from general_config.toml."""
    out = []
    for line in text.splitlines():
        stripped = line.lstrip()
        if stripped.startswith("personal_webhook"):
            out.append('personal_webhook = ""')
        elif stripped.startswith("discord_id"):
            out.append('discord_id = ""')
        elif stripped.startswith("player_tag"):
            out.append('player_tag = ""')
        elif stripped.startswith("last_public_ip"):
            out.append('last_public_ip = ""')
        else:
            out.append(line)
    return "\n".join(out) + ("\n" if not text.endswith("\n") else "")


README_TEST = """\
PylaAI — sharing build for testing
====================================

This zip is a clean copy of PylaAI without my personal data, without the
bundled ~1 GB Python runtime, and without local logs / sessions.

QUICK INSTALL (Windows)
------------------------

1. Install Python 3.11 from https://www.python.org/downloads/release/python-3119/
   (CHECK "Add Python to PATH" during install).

2. Install LDPlayer 9 from https://www.ldplayer.net (or use any android
   emulator with ADB on a known port).

3. Open a terminal in the extracted PylaAI folder and run:

       py -3.11 -m pip install --upgrade pip wheel setuptools
       py -3.11 setup.py install

   The setup script auto-detects your GPU and installs the matching torch /
   onnxruntime build (NVIDIA → CUDA, AMD/Intel → DirectML, otherwise CPU).

4. Open cfg/general_config.toml and adjust:
       current_emulator = "LDPlayer"
       emulator_port    = 5555     (5555 for LD instance #0, 5557 for #1, …)

   (Optional) For the Brawl Stars API trophy auto-fill, drop your own token
   into cfg/brawl_stars_api.toml — I removed mine.

5. Start the bot:

       run.bat

   Browser opens at http://127.0.0.1:8765 → choose a brawler → Start.

MULTI-EMULATOR (the new feature)
---------------------------------

After it boots, go to the "Инстансы" tab → "+ Добавить инстанс" → pick
LDPlayer → click "🔎 Найти LDPlayer-инстансы" to auto-discover your VMs.
Each instance runs as its own subprocess and can have its own brawler/target
through the "✎ Сессия" button on its card. The Dashboard "Run on:" panel
broadcasts a single click to all selected instances.

WHAT'S NOT INCLUDED
--------------------

- _internal/  — 932 MB PyInstaller runtime that backs setup.exe. Not needed
                if you have Python 3.11 installed; setup.py installs deps via
                pip directly.
- logs/       — my local log history.
- instances/  — my local per-emulator state.
- cfg/match_log.jsonl, cfg/adaptive_state.json — my personal stats.

SECRETS
--------

I scrubbed:
  - cfg/brawl_stars_api.toml (token, dev email/password, player tag)
  - cfg/webhook_config.toml  (Discord webhook URL)
  - cfg/general_config.toml  (personal_webhook, player_tag, last_public_ip)

You'll need to fill these in for yourself if you want trophy autofill or
Discord notifications.
"""


# ------------------------------------------------------------------
# Build
# ------------------------------------------------------------------
def should_skip_dir(rel_parts: tuple[str, ...]) -> bool:
    return any(part in EXCLUDE_DIR_NAMES for part in rel_parts)


def should_skip_file(rel_path: str) -> bool:
    if rel_path.replace("\\", "/") in EXCLUDE_FILE_RELPATHS:
        return True
    if rel_path.endswith(EXCLUDE_FILE_SUFFIXES):
        return True
    return False


def main() -> None:
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUT
    out_path = out_path.resolve()
    print(f"[build-share] writing {out_path}")
    if out_path.exists():
        out_path.unlink()

    file_count = 0
    total_bytes = 0
    with zipfile.ZipFile(out_path, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for dirpath, dirnames, filenames in os.walk(ROOT):
            # Prune directories in-place so os.walk doesn't recurse into them.
            dirnames[:] = [d for d in dirnames if d not in EXCLUDE_DIR_NAMES]
            rel_dir = Path(dirpath).resolve().relative_to(ROOT)
            rel_parts = rel_dir.parts if str(rel_dir) != "." else ()
            if should_skip_dir(rel_parts):
                continue

            for fname in filenames:
                rel_path = (rel_dir / fname).as_posix() if rel_parts else fname
                if should_skip_file(rel_path):
                    continue

                src = Path(dirpath) / fname

                # Scrubbed files: write sanitized content instead.
                if rel_path in SCRUBBED_FILES:
                    zf.writestr(f"PylaAI/{rel_path}", SCRUBBED_FILES[rel_path])
                    file_count += 1
                    total_bytes += len(SCRUBBED_FILES[rel_path])
                    print(f"  scrub  {rel_path}")
                    continue

                # Scrub general_config.toml in-place: keep most fields,
                # blank out the personal/sensitive ones.
                if rel_path == "cfg/general_config.toml":
                    try:
                        text = src.read_text(encoding="utf-8-sig")
                    except Exception:
                        text = src.read_text(encoding="utf-8", errors="replace")
                    cleaned = scrub_general_config(text)
                    zf.writestr(f"PylaAI/{rel_path}", cleaned)
                    file_count += 1
                    total_bytes += len(cleaned)
                    print(f"  scrub  {rel_path}")
                    continue

                try:
                    zf.write(src, f"PylaAI/{rel_path}")
                    file_count += 1
                    total_bytes += src.stat().st_size
                except Exception as exc:
                    print(f"  SKIP   {rel_path} ({exc})")

        # Friend-facing README at the root of the zip.
        zf.writestr("PylaAI/README_TEST.txt", README_TEST)
        file_count += 1
        total_bytes += len(README_TEST)

    final_size = out_path.stat().st_size
    print(f"[build-share] done: {file_count} files, raw {total_bytes/1024/1024:.1f} MB, "
          f"compressed {final_size/1024/1024:.1f} MB")
    print(f"[build-share] output: {out_path}")


if __name__ == "__main__":
    main()
